### ISSUE TITLE
feat: Implement automated semantic versioning and changelog generation

### ISSUE THREAD

**Issue by jbrinkman** [jbrinkman/ghi#12]
## Feature Description

Add automated semantic versioning and changelog generation to the project using go-semantic-release.

### Current State
- Version numbers are manually managed
- No automated changelog generation
- No standardized release process

### Desired Behavior
Implement automated semantic versioning and release management using [go-semantic-release](https://github.com/go-semantic-release/semantic-release) that will:

1. Automatically determine version numbers based on conventional commit messages
2. Generate changelogs automatically from commit history
3. Create GitHub releases with proper tagging
4. Ensure consistent release artifacts

#### Required Setup
- Add semantic-release configuration
- Configure CI/CD pipeline to handle releases
- Set up proper GitHub token permissions
- Configure changelog generation rules

#### Expected Workflow
1. Developers write conventional commit messages
2. On merge to main branch:
   - Analyze commits since last release
   - Determine next version number
   - Generate changelog
   - Create GitHub release
   - Tag the release
   - Publish artifacts

### Benefits
- Consistent version numbering
- Automated changelog generation
- Reduced manual release work
- Better release documentation
- Enforced commit message standards

### Technical Requirements
- Configure CI/CD (GitHub Actions) for release automation
- Set up proper GitHub authentication
- Define changelog templates
- Configure semantic-release rules

### Configuration Needs
```yaml
# Example semantic-release config structure
version: 1
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - '@semantic-release/changelog'
```

### Questions to Consider
 - What level of detail should be included in changelogs?
 - Should we implement custom rules for version bumping?
 - How should we handle pre-releases or beta versions?
 - What should the changelog template look like?
